/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.Controller;
import controller.ControllerExit;
import controller.IZaposleni;
import java.awt.Dimension;
import java.awt.Toolkit;

import java.sql.SQLException;
import java.util.EventObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Zaposleni;

/**
 *
 * @author I
 */
public class DnevniIzvestajForm extends javax.swing.JPanel implements IZaposleni {
    String datum = Controller.setDatum();
    Zaposleni zaposleni;
    JOptionPane op = new JOptionPane();
    
    
    public DnevniIzvestajForm() throws SQLException {
        initComponents();
        jLabel1.setText("Dnevni Izvestaj: " + Controller.setDnevniIzvestajId());
        jLabel3.setText(datum);
        jTable1 = Controller.setJTableDnevniIzvestaj2(jTable1);
        
        /*Layout --pocetak*/
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
       
        int height = (dimension.height-ControllerExit.Height51p)/2;
        int width = (dimension.width-ControllerExit.Width19p)/2;
        //200 /40
        jLabel1.setBounds(width, height, ControllerExit.Width12p, ControllerExit.Height4p);
         //130 /40
        jLabel2.setBounds(width, height+ControllerExit.Height9p, ControllerExit.Width8p, ControllerExit.Height4p);
         //170 /40
        jLabel3.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height9p, ControllerExit.Width10p, ControllerExit.Height4p);
        
        jScrollPane1.setBounds(width-ControllerExit.Width10p, height + ControllerExit.Height14p, ControllerExit.Width39p, ControllerExit.Height29p);
        
        jButton1.setBounds(width+ControllerExit.Width06p,height + ControllerExit.Height45p, ControllerExit.Width8p,ControllerExit.Height4p);
        jButton2.setBounds(width+ControllerExit.Width10p,height + ControllerExit.Height45p, ControllerExit.Width8p,ControllerExit.Height4p );
        
        /*Layout --kraj*/  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Dnevni izvestaj:");
        add(jLabel1);
        jLabel1.setBounds(121, 11, 155, 24);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Datum:");
        add(jLabel2);
        jLabel2.setBounds(60, 53, 73, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("jLabel3");
        add(jLabel3);
        jLabel3.setBounds(143, 60, 71, 22);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);

        add(jScrollPane1);
        jScrollPane1.setBounds(60, 99, 320, 91);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Sacuvaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(109, 250, 93, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Nazad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(190, 250, 81, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {        
            Controller.saveDnevniIzvestaj(datum, zaposleni.getId(), jTable1, 1, op);
            switch (zaposleni.getTipZaposlenog()){
                case 1:
                    MenuZaposleni mz = MenuZaposleni.mz;
                    zaposleni.addEventListener(mz);
                    zaposleni.distributeEvent();
                    Login.pocetniFrejm.setContentPane(mz);
                    Login.pocetniFrejm.revalidate();
                break;
                case 2:
                    MenuMenadzeri mm = MenuMenadzeri.mm;
                    zaposleni.addEventListener(mm);
                    zaposleni.distributeEvent();
                    Login.pocetniFrejm.setContentPane(mm);
                    Login.pocetniFrejm.revalidate();
                break;
            }
        } catch (SQLException ex) {
            Logger.getLogger(DnevniIzvestajForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       switch (zaposleni.getTipZaposlenog()){
                case 1:
                    MenuZaposleni mz = MenuZaposleni.mz;
                    zaposleni.addEventListener(mz);
                    zaposleni.distributeEvent();
                    Login.pocetniFrejm.setContentPane(mz);
                    Login.pocetniFrejm.revalidate();
                break;
                case 2:
                    MenuMenadzeri mm = MenuMenadzeri.mm;
                    zaposleni.addEventListener(mm);
                    zaposleni.distributeEvent();
                    Login.pocetniFrejm.setContentPane(mm);
                    Login.pocetniFrejm.revalidate();
                break;
            }
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void zaposleniUlogovan(EventObject evt) {
        zaposleni = (Zaposleni) evt.getSource();
    }
}
