/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerExit;
import controller.IZaposleni;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.EventObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Zaposleni;


public class MenuMenadzeri extends javax.swing.JPanel implements IZaposleni {

    Zaposleni zaposleni;
    public static MenuMenadzeri mm;
    
    public MenuMenadzeri() {
        initComponents();
        mm=this;
        
         /*Layout --pocetak*/
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int height = ((dimension.height-ControllerExit.Height62p)/2)-ControllerExit.Height10p;
        int width = (dimension.width-ControllerExit.Width39p)/2;
        jLabel1.setBounds(width, height, ControllerExit.Width12p, ControllerExit.Height5p);
        jLabel2.setBounds(width+ControllerExit.Width27p, height, ControllerExit.Width12p, ControllerExit.Height5p);
        jButtonNabavke.setBounds(width, height+ControllerExit.Height7p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButton8.setBounds(width+ControllerExit.Width27p, height+ControllerExit.Height7p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButtonProizvod.setBounds(width, height+ControllerExit.Height13p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButton9.setBounds(width+ControllerExit.Width27p, height+ControllerExit.Height13p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButtonDobavljac.setBounds(width, height+ControllerExit.Height20p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButton10.setBounds(width+ControllerExit.Width27p, height+ControllerExit.Height20p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButtonDnevniIzv.setBounds(width, height+ControllerExit.Height27p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButton11.setBounds(width+ControllerExit.Width27p, height+ControllerExit.Height27p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButtonTipPr.setBounds(width, height+ControllerExit.Height33p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButton12.setBounds(width+ControllerExit.Width27p, height+ControllerExit.Height33p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButtonTrosak.setBounds(width, height+ControllerExit.Height40p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButton13.setBounds(width+ControllerExit.Width27p, height+ControllerExit.Height40p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButtonZaposleni.setBounds(width, height+ControllerExit.Height47p, ControllerExit.Width12p, ControllerExit.Height5p);
        jButton14.setBounds(width+ControllerExit.Width27p, height+ControllerExit.Height47p, ControllerExit.Width12p, ControllerExit.Height5p);
        
        jButton1.setBounds(width+ControllerExit.Width13p, height+ControllerExit.Height57p, ControllerExit.Width12p, ControllerExit.Height5p);
        /*Layout --kraj*/  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonNabavke = new javax.swing.JButton();
        jButtonProizvod = new javax.swing.JButton();
        jButtonDobavljac = new javax.swing.JButton();
        jButtonDnevniIzv = new javax.swing.JButton();
        jButtonTipPr = new javax.swing.JButton();
        jButtonTrosak = new javax.swing.JButton();
        jButtonZaposleni = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setLayout(null);

        jButtonNabavke.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButtonNabavke.setText("Nabavka");
        jButtonNabavke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNabavkeActionPerformed(evt);
            }
        });
        add(jButtonNabavke);
        jButtonNabavke.setBounds(40, 27, 179, 35);

        jButtonProizvod.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButtonProizvod.setText("Proizvod");
        jButtonProizvod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProizvodActionPerformed(evt);
            }
        });
        add(jButtonProizvod);
        jButtonProizvod.setBounds(40, 70, 179, 35);

        jButtonDobavljac.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButtonDobavljac.setText("Dobavljac");
        jButtonDobavljac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDobavljacActionPerformed(evt);
            }
        });
        add(jButtonDobavljac);
        jButtonDobavljac.setBounds(40, 111, 179, 35);

        jButtonDnevniIzv.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButtonDnevniIzv.setText("Dnevni izvestaj");
        jButtonDnevniIzv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDnevniIzvActionPerformed(evt);
            }
        });
        add(jButtonDnevniIzv);
        jButtonDnevniIzv.setBounds(40, 152, 179, 35);

        jButtonTipPr.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButtonTipPr.setText("Tip proizvoda");
        jButtonTipPr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTipPrActionPerformed(evt);
            }
        });
        add(jButtonTipPr);
        jButtonTipPr.setBounds(40, 193, 179, 35);

        jButtonTrosak.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButtonTrosak.setText("Troskovi");
        jButtonTrosak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTrosakActionPerformed(evt);
            }
        });
        add(jButtonTrosak);
        jButtonTrosak.setBounds(40, 234, 179, 35);

        jButtonZaposleni.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButtonZaposleni.setText("Zaposleni");
        jButtonZaposleni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonZaposleniActionPerformed(evt);
            }
        });
        add(jButtonZaposleni);
        jButtonZaposleni.setBounds(40, 275, 179, 35);

        jButton8.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton8.setText("Nabavke");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        add(jButton8);
        jButton8.setBounds(229, 29, 191, 35);

        jButton9.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton9.setText("Dnevni izvestaji");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        add(jButton9);
        jButton9.setBounds(229, 70, 191, 35);

        jButton10.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton10.setText("Proizvodi");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        add(jButton10);
        jButton10.setBounds(229, 111, 191, 35);

        jButton11.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton11.setText("Dobavljaci");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        add(jButton11);
        jButton11.setBounds(229, 152, 191, 35);

        jButton12.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton12.setText("Tipovi proizvoda");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        add(jButton12);
        jButton12.setBounds(229, 193, 191, 35);

        jButton13.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton13.setText("Troskovi");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        add(jButton13);
        jButton13.setBounds(229, 234, 191, 35);

        jButton14.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton14.setText("Zaposleni");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        add(jButton14);
        jButton14.setBounds(229, 275, 191, 35);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Unos: ");
        add(jLabel1);
        jLabel1.setBounds(40, 0, 179, 21);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel2.setText("Pregled: ");
        add(jLabel2);
        jLabel2.setBounds(229, 4, 191, 19);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jButton1.setText("Trenutno stanje ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(137, 336, 193, 35);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNabavkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNabavkeActionPerformed
        try {
            NabavkaForm nf = new NabavkaForm();
            Login.pocetniFrejm.setContentPane(nf);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(nf);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
                Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonNabavkeActionPerformed

    private void jButtonProizvodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProizvodActionPerformed
        try{
            ProizvodForm pf = new ProizvodForm ();
            Login.pocetniFrejm.setContentPane(pf);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(pf);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonProizvodActionPerformed

    private void jButtonDobavljacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDobavljacActionPerformed
      
        DobavljacForm df = new DobavljacForm();
        Login.pocetniFrejm.setContentPane(df);
        Login.pocetniFrejm.revalidate();
        zaposleni.addEventListener(df);
        zaposleni.distributeEvent();
        
    }//GEN-LAST:event_jButtonDobavljacActionPerformed

    private void jButtonDnevniIzvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDnevniIzvActionPerformed
        try {
            DnevniIzvestajForm di = new DnevniIzvestajForm();
            Login.pocetniFrejm.setContentPane(di);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(di);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDnevniIzvActionPerformed

    private void jButtonTipPrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTipPrActionPerformed
        TipProizvodaForm tpf = new TipProizvodaForm();
        Login.pocetniFrejm.setContentPane(tpf);
        Login.pocetniFrejm.revalidate();
        zaposleni.addEventListener(tpf);
        zaposleni.distributeEvent();
    }//GEN-LAST:event_jButtonTipPrActionPerformed

    private void jButtonTrosakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTrosakActionPerformed
        try {
            TroskoviForm tf = new TroskoviForm();
            Login.pocetniFrejm.setContentPane(tf);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(tf);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonTrosakActionPerformed

    private void jButtonZaposleniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonZaposleniActionPerformed
         try {
            ZaposleniForm zf = new ZaposleniForm();
            Login.pocetniFrejm.setContentPane(zf);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(zf);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonZaposleniActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        try {
            NabavkaOut no = new NabavkaOut ();
            Login.pocetniFrejm.setContentPane(no);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(no);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        try {
            DnevniIzvestajOut dio = new DnevniIzvestajOut();
            Login.pocetniFrejm.setContentPane(dio);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(dio);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        try {
            ProizvodiOut po = new ProizvodiOut();
            Login.pocetniFrejm.setContentPane(po);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(po);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
            DobavljacOut dobavljacOut = new DobavljacOut ();
            Login.pocetniFrejm.setContentPane(dobavljacOut);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(dobavljacOut);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        try {
            TipoviProizvodaOut tipPOut = new TipoviProizvodaOut();
            Login.pocetniFrejm.setContentPane(tipPOut);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(tipPOut);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
        try {
            TroskoviOut tr = new TroskoviOut();
            Login.pocetniFrejm.setContentPane(tr);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(tr);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        try {
            ZaposleniOut za = new ZaposleniOut();
            Login.pocetniFrejm.setContentPane(za);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(za);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            TrenutnoStanje ts = new TrenutnoStanje();
            Login.pocetniFrejm.setContentPane(ts);
            Login.pocetniFrejm.revalidate();
            zaposleni.addEventListener(ts);
            zaposleni.distributeEvent();
        } catch (SQLException ex) {
            Logger.getLogger(MenuMenadzeri.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JButton jButtonDnevniIzv;
    private javax.swing.JButton jButtonDobavljac;
    private javax.swing.JButton jButtonNabavke;
    private javax.swing.JButton jButtonProizvod;
    private javax.swing.JButton jButtonTipPr;
    private javax.swing.JButton jButtonTrosak;
    private javax.swing.JButton jButtonZaposleni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables

    
    /*Event-i --pocetak */
    @Override
    public void zaposleniUlogovan(EventObject evt) {
        zaposleni = (Zaposleni)evt.getSource();
    }
    
    
    
    /*Event-i --kraj*/
}
