/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import model.Nabavka;
import controller.Controller;
import controller.ControllerExit;
import controller.IZaposleni;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.EventObject;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import model.Dobavljac;
import model.Proizvod;
import model.TipTroska;
import model.Zaposleni;

/**
 *
 * @author I
 */
public class NabavkaForm extends javax.swing.JPanel implements IZaposleni {
        String datum = Controller.setDatum();
        Zaposleni zaposleni;
        JOptionPane op = new JOptionPane();
        public static NabavkaForm nabavka;
        
    public NabavkaForm() throws SQLException {
        
        initComponents();
        
        jLabel1.setText("Nabavka: " + Controller.setNabavkaId() );
        jLabel5.setText(datum);
        jRadioButton1.setActionCommand("1");
        jRadioButton2.setActionCommand("2");
        jRadioButton1.setText(TipTroska.getTipTroska(1).getNaziv());
        jRadioButton2.setText(TipTroska.getTipTroska(2).getNaziv());
        jList1.setModel(Controller.setJlistModelOfDobavljac());
        jTable1 = Controller.setJTableProizvodi2(jTable1);
        nabavka = this;
        
        /*Layout --pocetak*/
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int height = (dimension.height-ControllerExit.Height84p)/2;
        int width = (dimension.width-ControllerExit.Width19p)/2;
        jLabel1.setBounds(width, height, ControllerExit.Width9p, ControllerExit.Height4p);
        jLabel2.setBounds(width, height+ControllerExit.Height9p, ControllerExit.Width8p, ControllerExit.Height4p);
        jLabel5.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height9p, ControllerExit.Width10p, ControllerExit.Height4p);
        jLabel3.setBounds(width, height+ControllerExit.Height12p, ControllerExit.Width8p, ControllerExit.Height4p);
        jScrollPane1.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height12p, ControllerExit.Width10p, ControllerExit.Height19p);
        jLabel4.setBounds(width, height+ControllerExit.Height35p, ControllerExit.Width8p, ControllerExit.Height4p);
        jRadioButton1.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height33p, ControllerExit.Width10p, ControllerExit.Height4p);
        jRadioButton2.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height38p, ControllerExit.Width10p, ControllerExit.Height4p);
        jScrollPane2.setBounds(width-ControllerExit.Width10p, height + ControllerExit.Height44p, ControllerExit.Width39p, ControllerExit.Height29p);
        jButton1.setBounds(width+ControllerExit.Width06p,height + ControllerExit.Height80p, ControllerExit.Width8p,ControllerExit.Height4p);
        jButton2.setBounds(width+ControllerExit.Width10p,height + ControllerExit.Height80p,ControllerExit.Width8p,ControllerExit.Height4p);
        
        /*Layout --kraj*/  
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel4 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(218, 11, 100, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Datum:");
        add(jLabel2);
        jLabel2.setBounds(117, 52, 51, 23);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Dobavljac:");
        add(jLabel3);
        jLabel3.setBounds(117, 81, 95, 23);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(218, 93, 94, 78);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Tip troska:");
        add(jLabel4);
        jLabel4.setBounds(117, 199, 96, 24);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Sacuvaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(162, 393, 93, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Nazad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(292, 393, 81, 31);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setText("jLabel5");
        add(jLabel5);
        jLabel5.setBounds(218, 52, 94, 23);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setText("jRadioButton1");
        add(jRadioButton1);
        jRadioButton1.setBounds(218, 189, 137, 31);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setText("jRadioButton2");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(jRadioButton2);
        jRadioButton2.setBounds(218, 212, 137, 31);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        add(jScrollPane2);
        jScrollPane2.setBounds(128, 241, 375, 108);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            try {
                Controller.saveNabavka(datum, jList1, zaposleni.getId(), buttonGroup1, jTable1, 1, 2,op);
                 switch(zaposleni.getTipZaposlenog()){
                    case 1:
                        MenuZaposleni mz2 = new MenuZaposleni();
                        zaposleni.addEventListener(mz2);
                        zaposleni.distributeEvent();
                        Login.pocetniFrejm.setContentPane(mz2);
                        Login.pocetniFrejm.revalidate(); 
                    break;
                    case 2:
                        MenuMenadzeri mm = new MenuMenadzeri ();
                        zaposleni.addEventListener(mm);
                        zaposleni.distributeEvent();
                        Login.pocetniFrejm.setContentPane(mm);
                        Login.pocetniFrejm.revalidate();
                    break;
                }
            } catch (NullPointerException ex){
                op.showMessageDialog(op.getParent(),"Neispravan odabir podataka. Molimo vas pokusajte ponovo!","Upozorenje",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            } catch (SQLException ex) {
                Logger.getLogger(NabavkaForm.class.getName()).log(Level.SEVERE, null, ex);
            } catch (Exception ex){
                op.showMessageDialog(op.getParent(),"Greska. Molimo vas pokusajte ponovo!","Greska",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
                
            }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        switch(zaposleni.getTipZaposlenog()){
            case 1:
                MenuZaposleni mz2 = new MenuZaposleni();
                zaposleni.addEventListener(mz2);
                zaposleni.distributeEvent();
                Login.pocetniFrejm.setContentPane(mz2);
                Login.pocetniFrejm.revalidate(); 
            break;
            case 2:
                MenuMenadzeri mm = new MenuMenadzeri ();
                zaposleni.addEventListener(mm);
                zaposleni.distributeEvent();
                Login.pocetniFrejm.setContentPane(mm);
                Login.pocetniFrejm.revalidate();
            break;
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables

    @Override
    public void zaposleniUlogovan(EventObject evt) {
        zaposleni = (Zaposleni) evt.getSource();
    }
}
