/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ControllerExit;
import controller.IZaposleni;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.EventObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import model.Zaposleni;

/**
 *
 * @author Mihailo
 */
public class TrenutnoStanje extends javax.swing.JPanel implements IZaposleni {
    Zaposleni zaposleni;
    JOptionPane op = new JOptionPane();
    
    
    public TrenutnoStanje() throws SQLException {
        initComponents();
        jList1.setModel(ControllerExit.setJListModel(1, 10));
        jList2.setModel(ControllerExit.setJListModel(2, 10));
        jList3.setModel(ControllerExit.setJListModel(3, 10));
        ControllerExit.setJTableTrenutnoStanjeStart(jTable1,jLabelUlaz,jLabelIzlaz,jLabelUkupno);
        
        
         /*Layout --pocetak*/
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int height = ((dimension.height-ControllerExit.Height70p)/2)-ControllerExit.Height10p;
        int width = (dimension.width-ControllerExit.Width39p)/2;
        
        jToggleButton1.setBounds(width, height, ControllerExit.Width10p, ControllerExit.Height4p);
        jToggleButton2.setBounds(width+ControllerExit.Width13p, height, ControllerExit.Width10p, ControllerExit.Height4p);
        jToggleButton3.setBounds(width+ControllerExit.Width25p, height, ControllerExit.Width10p,ControllerExit.Height4p);
        
        jScrollPane1.setBounds(width, height+ControllerExit.Height6p, ControllerExit.Width10p, ControllerExit.Height14p);
        jScrollPane2.setBounds(width+ControllerExit.Width13p, height+ControllerExit.Height6p, ControllerExit.Width10p, ControllerExit.Height14p);
        jScrollPane3.setBounds(width+ControllerExit.Width25p, height+ControllerExit.Height6p, ControllerExit.Width10p, ControllerExit.Height14p);
        
        jScrollPane4.setBounds(width, height+ControllerExit.Height23p, ControllerExit.Width39p, ControllerExit.Height29p);
        jLabel2.setBounds(width, height+ControllerExit.Height53p, ControllerExit.Width9p, ControllerExit.Height4p);
        jLabelUlaz.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height53p, ControllerExit.Width9p, ControllerExit.Height4p);
        jLabel3.setBounds(width+ControllerExit.Width20p, height+ControllerExit.Height53p, ControllerExit.Width9p, ControllerExit.Height4p);
        jLabelIzlaz.setBounds(width+ControllerExit.Width30p, height+ControllerExit.Height53p, ControllerExit.Width9p, ControllerExit.Height4p);
        jLabel5.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height59p, ControllerExit.Width10p, ControllerExit.Height4p);
        jLabelUkupno.setBounds(width+ControllerExit.Width19p, height+ControllerExit.Height59p, ControllerExit.Width10p, ControllerExit.Height4p);
        
        jButton1.setBounds(width+ControllerExit.Width10p,height + ControllerExit.Height65p, ControllerExit.Width8p,ControllerExit.Height4p);
        jButton2.setBounds(width+ControllerExit.Width20p,height + ControllerExit.Height65p, ControllerExit.Width8p,ControllerExit.Height4p);
        
        /*Layout --kraj*/ 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList3 = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabelUlaz = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabelIzlaz = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelUkupno = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        jToggleButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton1.setText("Dan:");
        add(jToggleButton1);
        jToggleButton1.setBounds(77, 33, 105, 31);

        jToggleButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton2.setText("Mesec:");
        add(jToggleButton2);
        jToggleButton2.setBounds(278, 36, 105, 31);

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jToggleButton3.setText("Godina:");
        add(jToggleButton3);
        jToggleButton3.setBounds(523, 36, 105, 31);

        jList1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(jList1);

        add(jScrollPane1);
        jScrollPane1.setBounds(77, 70, 105, 86);

        jList2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList2.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(jList2);

        add(jScrollPane2);
        jScrollPane2.setBounds(278, 70, 105, 86);

        jList3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jList3.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jList3.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(jList3);

        add(jScrollPane3);
        jScrollPane3.setBounds(523, 70, 105, 86);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jTable1);

        add(jScrollPane4);
        jScrollPane4.setBounds(77, 165, 551, 207);

        jLabelUlaz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelUlaz.setText("jLabel1");
        add(jLabelUlaz);
        jLabelUlaz.setBounds(170, 413, 83, 27);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Ulaz:");
        add(jLabel2);
        jLabel2.setBounds(81, 413, 83, 27);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Izlaz:");
        add(jLabel3);
        jLabel3.setBounds(419, 413, 83, 27);

        jLabelIzlaz.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabelIzlaz.setText("jLabel1");
        add(jLabelIzlaz);
        jLabelIzlaz.setBounds(508, 413, 106, 27);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel5.setText("Trenutno stanje: ");
        add(jLabel5);
        jLabel5.setBounds(211, 458, 106, 27);

        jLabelUkupno.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabelUkupno.setText("jLabel1");
        add(jLabelUkupno);
        jLabelUkupno.setBounds(364, 458, 106, 27);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Odaberi");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(274, 503, 93, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Nazad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(355, 503, 81, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            //Table setJTableTrenutnoStanje (JTable j,JLabel jlUlaz,JLabel jlIzlaz,JLabel jlUkupno,JToggleButton tb1,JToggleButton tb2,JToggleButton tb3,int id,JOptionPane op)

            ControllerExit.setJTableTrenutnoStanje(jTable1, jLabelUlaz, jLabelIzlaz, jLabelUkupno, jToggleButton1, jToggleButton2, jToggleButton3,jList1,jList2,jList3, op);
        } catch (SQLException ex) {
            Logger.getLogger(TrenutnoStanje.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuMenadzeri mm = MenuMenadzeri.mm;
        Login.pocetniFrejm.setContentPane(mm);
        Login.pocetniFrejm.revalidate();
        zaposleni.addEventListener(mm);
        zaposleni.distributeEvent();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelIzlaz;
    private javax.swing.JLabel jLabelUkupno;
    private javax.swing.JLabel jLabelUlaz;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JList<String> jList3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables

    @Override
    public void zaposleniUlogovan(EventObject evt) {
        zaposleni = (Zaposleni)evt.getSource();
    }
}
