/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.sql.SQLException;
import model.TipTroska;
import controller.Controller;
import controller.ControllerExit;
import controller.IFirstLogin;
import controller.IZaposleni;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.EventObject;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.plaf.OptionPaneUI;
import model.Zaposleni;


public class ZaposleniForm extends javax.swing.JPanel implements IFirstLogin, IZaposleni{

    String ime;
    String adresa;
    String telefon;
    String lozinka;
    public Zaposleni zaposleniFirstLogin;
    public boolean zapFirstLogin;
    JOptionPane op = new JOptionPane();
    Zaposleni zaposleni;
    
    
    public ZaposleniForm() throws SQLException {
        initComponents();
        jRadioButton1.setActionCommand("1");
        jRadioButton2.setActionCommand("2");
        jRadioButton1.setText("Radnik");
        jRadioButton2.setText("Menadzer");
        jRadioButton3.setActionCommand("1");
        jRadioButton4.setActionCommand("2");
        jRadioButton3.setText("Stalno zaposlen");
        jRadioButton4.setText("Zaposlen na odredjeno");
        
        /*Layout --pocetak*/
        Dimension dimension = Toolkit.getDefaultToolkit().getScreenSize();
        int height = ((dimension.height-ControllerExit.Height56p)/2)-ControllerExit.Height10p;
        int width = (dimension.width-ControllerExit.Width19p)/2;
        jLabel1.setBounds(width, height, ControllerExit.Width9p, ControllerExit.Height4p);
        jLabel2.setBounds(width, height+ControllerExit.Height9p, ControllerExit.Width8p, ControllerExit.Height4p);
        jTextField1.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height9p, ControllerExit.Width10p, ControllerExit.Height4p);
        jLabel3.setBounds(width, height+ControllerExit.Height14p, ControllerExit.Width8p, ControllerExit.Height4p);
        jTextField2.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height14p, ControllerExit.Width10p, ControllerExit.Height4p);
        jLabel4.setBounds(width, height+ControllerExit.Height20p, ControllerExit.Width8p, ControllerExit.Height4p);
        jTextField3.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height20p, ControllerExit.Width10p, ControllerExit.Height4p);
        jLabel5.setBounds(width, height+ControllerExit.Height27p, ControllerExit.Width8p, ControllerExit.Height4p);
        jRadioButton1.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height26p, ControllerExit.Width10p, ControllerExit.Height4p);
        jRadioButton2.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height30p, ControllerExit.Width10p, ControllerExit.Height4p);
        jLabel7.setBounds(width, height+ControllerExit.Height38p, ControllerExit.Width8p, ControllerExit.Height4p);
        jRadioButton3.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height36p, ControllerExit.Width10p, ControllerExit.Height4p);
        jRadioButton4.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height41p, ControllerExit.Width10p, ControllerExit.Height4p);
        jLabel6.setBounds(width, height+ControllerExit.Height47p, ControllerExit.Width8p, ControllerExit.Height4p);
        jPasswordField1.setBounds(width+ControllerExit.Width9p, height+ControllerExit.Height47p, ControllerExit.Width10p, ControllerExit.Height4p);
        
        jButton1.setBounds(width+ControllerExit.Width06p,height + ControllerExit.Height52p, ControllerExit.Width8p,ControllerExit.Height4p );
        jButton2.setBounds(width+ControllerExit.Width10p,height + ControllerExit.Height52p, ControllerExit.Width8p,ControllerExit.Height4p);
        /*Layout --kraj*/ 
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 22)); // NOI18N
        jLabel1.setText("Zaposleni:");
        add(jLabel1);
        jLabel1.setBounds(52, 11, 121, 23);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel2.setText("Ime i Prezime:");
        add(jLabel2);
        jLabel2.setBounds(52, 52, 87, 23);

        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(jTextField1);
        jTextField1.setBounds(149, 53, 101, 28);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel3.setText("Adresa:");
        add(jLabel3);
        jLabel3.setBounds(52, 81, 87, 23);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel4.setText("Telefon:");
        add(jLabel4);
        jLabel4.setBounds(52, 110, 87, 23);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel5.setText("Status:");
        add(jLabel5);
        jLabel5.setBounds(52, 227, 87, 23);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel6.setText("Lozinka:");
        add(jLabel6);
        jLabel6.setBounds(52, 326, 87, 23);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel7.setText("Pozicija:");
        add(jLabel7);
        jLabel7.setBounds(52, 161, 87, 23);

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(jTextField2);
        jTextField2.setBounds(149, 82, 101, 28);

        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(jTextField3);
        jTextField3.setBounds(149, 111, 101, 28);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton1.setText("jRadioButton1");
        add(jRadioButton1);
        jRadioButton1.setBounds(149, 140, 137, 31);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton2.setText("jRadioButton2");
        add(jRadioButton2);
        jRadioButton2.setBounds(149, 166, 137, 31);

        buttonGroup2.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton3.setText("jRadioButton3");
        add(jRadioButton3);
        jRadioButton3.setBounds(149, 227, 137, 31);

        buttonGroup2.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jRadioButton4.setText("jRadioButton4");
        add(jRadioButton4);
        jRadioButton4.setBounds(149, 257, 137, 31);

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        add(jPasswordField1);
        jPasswordField1.setBounds(149, 320, 212, 34);

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Sacuvaj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1);
        jButton1.setBounds(125, 385, 93, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("Nazad");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        add(jButton2);
        jButton2.setBounds(214, 385, 81, 31);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        ime = jTextField1.getText();
        adresa = jTextField2.getText();
        telefon = jTextField3.getText();
        jPasswordField1.selectAll();
        lozinka = jPasswordField1.getSelectedText();
        try {
            Controller.saveZaposleni(ime, adresa, telefon, buttonGroup2, buttonGroup1, lozinka,op);
            
            
            if(zapFirstLogin){
                Controller.firstLoginInput(op, this);
            }
            
            MenuMenadzeri mm = MenuMenadzeri.mm;
            zaposleni.addEventListener(mm);
            zaposleni.distributeEvent();
            Login.pocetniFrejm.setContentPane(mm);
            Login.pocetniFrejm.revalidate();
        }catch (NullPointerException ex){
            op.showMessageDialog(op.getParent(),"Neispravan unos podataka. Molimo vas pokusajte ponovo! ","Neispravan unos",JOptionPane.ERROR_MESSAGE);
        }
        catch (SQLException ex) {
            Logger.getLogger(ZaposleniForm.class.getName()).log(Level.SEVERE, null, ex);
            op.showMessageDialog(op.getParent(),"Ime: "+ ime + " vec postoji! Molimo vas da promenite ime i da pokusate ponovo!","Neispravan unos",JOptionPane.ERROR_MESSAGE);
        }catch (Exception ex){
            op.showMessageDialog(op.getParent(),"Greska! Molimo vas pokusajte ponovo! ","Greska",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        MenuMenadzeri mm = MenuMenadzeri.mm;
            zaposleni.addEventListener(mm);
            zaposleni.distributeEvent();
            Login.pocetniFrejm.setContentPane(mm);
            Login.pocetniFrejm.revalidate();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    @Override
    public boolean firstLogin(EventObject evt) {
        zaposleniFirstLogin = (Zaposleni)evt.getSource();
        zapFirstLogin=true;
        return zapFirstLogin;
    }

    @Override
    public void zaposleniUlogovan(EventObject evt) {
        zaposleni = (Zaposleni)evt.getSource();
    }
}
